name: e_commerce_final
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.5.3
  google_sign_in: ^7.2.0
  icons_launcher: ^3.0.3
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  get_it: ^8.2.0
  flutter_conditional_rendering: ^2.1.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  page_transition: ^2.2.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  go_router: ^16.2.5
  animations: ^2.1.0
  font_awesome_flutter: ^10.9.1
  pinput: ^5.0.2
  otp_timer_button: ^1.1.1
  flutter_phoenix: ^1.1.1
  device_preview: ^1.3.1

# dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# splash screen

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png

# Icon app

icons_launcher:
  image_path: "assets/images/shopping.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/shopping.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Hanimation
      fonts:
        - asset: assets/fonts/Hanimation_Arabic_Regular.otf

flutter_intl:
  enabled: true
